#ifndef __SYNC_DEF_H__
#define __SYNC_DEF_H__

#define SYNC_ERR_STR_ENOSPC		"No space left on device"
#define SYNC_ERR_STR_ENOENT		"No such file or directory"
#define SYNC_ERR_STR_EROFS		"Read-only file system"
#define SYNC_ERR_STR_EIO		"Input/output error"
#define SYNC_ERR_STR_EPERM		"Operation not permitted"

#define NETWORK_SYNC_DAEMON_RESPONSE_USAGE_WRONG	"NETWORK_SYNC_DAEMON_RESPONSE_USAGE_WRONG"
#define NETWORK_SYNC_DAEMON_RESPONSE_MOUNT_OK		"NETWORK_SYNC_DAEMON_RESPONSE_MOUNT_OK"
#define NETWORK_SYNC_DAEMON_RESPONSE_MOUNT_FAIL		"NETWORK_SYNC_DAEMON_RESPONSE_MOUNT_FAIL"
#define NETWORK_SYNC_DAEMON_RESPONSE_SYNC_OK		"NETWORK_SYNC_DAEMON_RESPONSE_SYNC_OK"
#define NETWORK_SYNC_DAEMON_RESPONSE_SYNC_FAIL		"NETWORK_SYNC_DAEMON_RESPONSE_SYNC_FAIL"

typedef enum _network_sync_daemon_type {
	NETWORK_SYNC_DAEMON_TYPE_CHECK_MOUNT=0,
	NETWORK_SYNC_DAEMON_TYPE_SYNC_DATA,
} NETWORK_SYNC_DAEMON_TYPE_E;
#endif /*end of __SYNC_DEF_H__*/
