#define	CONF_VERSION	"1.02.24"
#define	CONF_PRODUCT_EXT_IOM
#define	CONF_PRODUCT_EXT_IOM_X2
#define	CONF_CUSTOMER_NAME	"IOMEGA"
#define	CONF_MODEL_NAME	"IOM-554H"
#define	CONF_PRODUCT_SN	"PRODUCT_SN"
#define	CONF_UI_LOGIC_IOM
#define	CONF_BASIC_PAGES_GENERIC
#define	CONF_UI_LOGIC	"IOM_pages"
#define	CONF_OEM_IOM
#define	CONF_RESOURCE_IOM
#define	CONF_RESOURCE	"RES_IOM"
#define	CONF_EXTRA_RESOURCE	""
#define	CONF_MODEL_WW
#define	CONF_MODEL	"ww"
#define	CONF_TVDOCK
#define	CONF_PRODUCT	"TVDOCK"
#define	CONF_CONFIG_HEADER_TYPE	"A"
#define	CONF_CONFIG_HEADER_VERSION	"1"
#define	CONF_PLATFORM_SMP8654
#define	CONF_PLATFORM_SMP8654_ALPHA_IOM_BOARD
#define	CONF_COMPILE_WITH_GFLAG	""
#define	CONF_COMPILE_WITH_OPTIMIZE	"-O"
#define	CONF_PLATFORM_SMP8654_SDK_3_8_8
#define	CONF_PLATFORM_SMP8654_SDK_SUBVERSION_rc_11
#define	CONF_SUPPORT_DCCHD
#define	CONF_SUPPORT_DCCHD_DVD_BD_NAVIGATION
#define	CONF_3_8_8_RC11_AQUA
#define	CONF_DCCHD_VERSION	"SMP8652_3_8_8_rc_11_aqua.mips"
#define	CONF_DCCHD_MMAP_CONFIG_FILE	""
#define	CONF_DIRECTFBRC_BUILDER
#define	CONF_USE_DIRECTFB_PORTING_SOURCECODE
#define	CONF_DIRECTFB_PORTING_VERSION	"SMP8654_3_8_8_rc_11_porting.mips"
#define	CONF_DIRECTFB_OVERWRITE_SIMGA_PNG_PATCH
#define	CONF_DIRECTFB_HDMI_FIX_1080P24_SWITCHING
#define	CONF_DIRECTFB_FIX_COLOR_SPACE
#define	CONF_DIRECTFB_FIX_CRASH_IN_INVALID_ISO
#define	CONF_DCCHD_FIX_HDMI_SPD_WORDS
#define	CONF_PLATFORM_SMP8654_SDK_3_8_7_ORIGINAL_KERNEL_PATCH
#define	CONF_PLATFORM_SMP8654_TOOLCHAIN_GNU_4_3_2
#define	CONF_SIGMA_EZBOOT_0XAA_NAND_FLASH_DRIVER
#define	CONF_SIGMA_YAMON_R2_13_31_NAND_FLASH_DRIVER
#define	CONF_LINUX_KERNEL_2_6_22_19_36_NAND_FLASH_DRIVER
#define	CONF_DTS_CHIP_SET
#define	CONF_HAVE_VIDEO_CODEC_RMVB
#define	CONF_TOOLCHAIN_FILENAME	"mips-4.3.tgz"
#define	CONF_CROSS_BIN	"/opt/mips-4.3/bin/"
#define	CONF_CROSS	"$(CROSS_BIN)/mipsel-linux-"
#define	CONF_CROSS_PREFIX	"/opt/mips-4.3/"
#define	CONF_SIGMA_SDK_VERSION	"3_8_0"
#define	CONF_SIGMA_ISDK_VERSION	"ISDK_3_8_5_rc_2-1"
#define	CONF_BUILD_DMAOSD
#define	CONF_BUILD_DMARENDER
#define	CONF_BUILD_MISC
#define	CONF_BUILD_MEDIALOGIC
#define	CONF_BUILD_EXTERNAL_PACKAGES
#define	CONF_BUILD_ROOTFS
#define	CONF_BUILD_ROOTFS_PRIMARY_SYSTEM
#define	CONF_BUILD_FIRMWARE
#define	CONF_REPOSITORY_IP	"172.19.149.41"
#define	CONF_REPOSITORY_PATH	"dmax/trunk"
#define	CONF_DBUS
#define	CONF_ENABLE_NETWORKING
#define	CONF_WEB_SERVER_APACHE
#define	CONF_WEB_SERVER_APACHE_INSTALL_PATH	"/webserver"
#define	CONF_WEB_SERVER_PHP
#define	CONF_DMA_SLAVEMODE
#define	CONF_DMA_SLAVEMODE_SUPPORT_FF_REV_FUNCTION_FOR_VIDEO_PLAYING
#define	CONF_CHECK_CONNECTION_HOST	""
#define	CONF_LAN_INTERFACE	"eth0"
#define	CONF_ENABLE_AUTOIP
#define	CONF_WIRELESS_SUPPORT
#define	CONF_DROP_DUPLICATE_SSID
#define	CONF_WIRELESS_PROFILE_SUPPORT
#define	CONF_WIRELESS_PROFILE_NUM	5
#define	CONF_WIRELESS_PROFILE_PAGE_SUPPORT
#define	CONF_WIRELESS_TOOLS
#define	CONF_WLAN_INTERFACE	"eth1"
#define	CONF_WIRELESS_SITE_SURVEY_SORT_BY_SIGNAL_STRENGTH
#define	CONF_WIRELESS_RALINK_SOLUTION
#define	CONF_WIRELESS_USB_DONGLE
#define	CONF_WIRELESS_RT3070
#define	CONF_RT3070_VERSION_2_5_0_1
#define	CONF_WPA_SUPPLICANT
#define	CONF_NFS_MOUNT_POINT	""
#define	CONF_SAMBA
#define	CONF_SAMBA_VERSION_3_0_28A
#define	CONF_SAMBA_VERSION	"3.0.28a"
#define	CONF_SAMBA_WORKGROUP
#define	CONF_SAMBA_INSTALL_SMBCLIENT
#define	CONF_SAMBA_CONF_PATH	"/tmp/smb.conf"
#define	CONF_SAMBA_MOUNT_POINT	"/tmp"
#define	CONF_AUTO_LOGIN
#define	CONF_SAMBA_CLIENT_SUPPORT_SERVERLIST_REFRESH
#define	CONF_CLEAR_USERACCOUNT
#define	CONF_CLEAR_ALL_USERINFO
#define	CONF_SAMBA_CIFS_MOUNT_READ_WRITE
#define	CONF_SUPPORT_NETWORK_SYNC_DAEMON
#define	CONF_DMA_UPNP
#define	CONF_DEVICE_MODEL_DESC	"Iomega Multimedia Hard Disk"
#define	CONF_DEVICE_MODEL_NAME	"Iomega_HD"
#define	CONF_DEVICE_MODEL_NUM	"Iomega"
#define	CONF_DEVICE_MODEL_URL	"http://www.iomega.com"
#define	CONF_DEVICE_MANUFACTURER_URL	"http://www.iomega.com"
#define	CONF_DEVICE_MANUFACTURER_NAME	"Iomega"
#define	CONF_DMA_DLNA
#define	CONF_WMC_WITH_WRONG_BITRATE
#define	CONF_DEVICE_NAME	"Iomega_HD"
#define	CONF_HOME_ENTER_ALWAYS_SERVER_LIST
#define	CONF_MOVE_DEFAULT_M_SERVER_FIRST
#define	CONF_UPNP_MEDIA_SERVER_SUPPORT
#define	CONF_DMA_SUPPORT_LOOPBACK
#define	CONF_TWKY_PATH	""
#define	CONF_SAMBA_SERVER
#define	CONF_SAMBA_FTRUNCATE_PATCH
#define	CONF_SAMBA_SERVER_SCRIPT	"/bin/run_samba"
#define	CONF_SAMBA_SERVER_DESCRIPTIVE_COMMENT_STRING	"Iomega ClassicHD"
#define	CONF_SAMBA_SERVER_RENAME_DUPLICATE_NAME_METHOD2
#define	CONF_DMA_FLICKR
#define	CONF_FLICKR_API_KEY_IOM
#define	CONF_DMA_FLICKR_API_KEY	"5db9831846716a9917057bc4a7cbfce0"
#define	CONF_DMA_FLICKR_SCRECT_KEY	"bcbacb0458d39713"
#define	CONF_DMA_PANDORA
#define	CONF_OSSP
#define	CONF_DMA_MEDIAFLY
#define	CONF_MEDIAFLY_COMBINE_POPULAR_MYCHANNEL
#define	CONF_MEDIAFLY_MANAGER_USER_IN_DASHBOARD
#define	CONF_MEDIAFLY_MCODE_IN_DASHBOARD
#define	CONF_MEDIAFLY_COMBINE_CONTENT_SOURCE
#define	CONF_MEDIAFLY_SEARCH_WITH_SEARCHTYPE
#define	CONF_MEDIAFLY_API_3_0
#define	CONF_MEDIAFLY_OFFICIAL_PROFILE
#define	CONF_USE_PANDORA_OFFICAL_URL
#define	CONF_PANDORA_SUPPORT_AUTOCOMPLETE
#define	CONF_DMA_YOUTUBE
#define	CONF_DMA_YOUTUBE_PRODUCT_NAME	"HDDigitalMediaPlayer"
#define	CONF_DMA_YOUTUBE_CLIENT_ID	"ytapi-MyMediaPlayer-1234567-0"
#define	CONF_DMA_YOUTUBE_DEVELOPER_KEY	"AI39si6qtU8Yk71b6FVhnFqPIUsZKLG0_ypuJuilP4Hal5Sot0GJNJKMTaJ9bt5bdhNu8Yw5UZmbcpM4abyA_wtH1ZJsQWxMsQ"
#define	CONF_DMA_YOUTUBE_DEVELOPER_SECRET	""
#define	CONF_DMA_YOUTUBE_SWF_IMPL
#define	CONF_LACIE_BONJOUR_MODEL_NAME	""
#define	CONF_DMA_BT_SCRIPT	""
#define	CONF_DMA_BT_PAUSE_SCRIPT	""
#define	CONF_DMA_BT_RESUME_SCRIPT	""
#define	CONF_DMA_NZB_SCRIPT	""
#define	CONF_FLASHLITE3
#define	CONF_FLASHLITE3_WITHOUT_EDK
#define	CONF_FLASHLITE3_VERSION	"SMP8654_1.2.206-3_8_8_rc_16-1.mips"
#define	CONF_NETFLIX_VERSION	"v2.0.4-091027-02"
#define	CONF_SIGMA_NETFLIX_VERSION	""
#define	CONF_SIGMA_NETFLIX_PATCH_REDUCE_CPU_USAGE
#define	CONF_SIGMA_NETFLIX_PATCH_CRASH_WHEN_EXIT_IMMEDIATELY
#define	CONF_NETFLIX_SYSTEM_DATA_FILE	""
#define	CONF_NETFLIX_SYSTEM_DATA_SECURE_FILE	""
#define	CONF_NETFLIX_ACCOUNT_ACTIVATED_FILE	""
#define	CONF_DMA_RUN_SWF
#define	CONF_METADATA_TAGGING
#define	CONF_METADATA_AUTO_TAGGING
#define	CONF_METADATA_SCRAPER_FOLDER	"/osd/"
#define	CONF_METADATA_SUPPORT_MULTILANGUAGE
#define	CONF_METADATA_VIEW_BACKDROP_PHOTOS
#define	CONF_WEATHER
#define	CONF_METADATA_TAGGING_LIB
#define	CONF_WEATHER_SIMPLE_MODE
#define	CONF_WEATHER_GET_DEFAULT_CITY_FROM_CONFIG_FILE
#define	CONF_VUDU_VERSION	""
#define	CONF_VUDU_STORAGE_PATH	""
#define	CONF_VUDU_APP_STORAGE_PATH	""
#define	CONF_QT_WEB_KIT
#define	CONF_QT_4_5_0
#define	CONF_QT_VERSION	"4.5.0-1.2"
#define	CONF_BROWSER_HOMEPAGE_URL	""
#define	CONF_ESPIAL_BROWSER
#define	CONF_ESPIAL_SDK_20111026
#define	CONF_ESPIAL_SDK_VERSION	"20111026"
#define	CONF_ESPIAL_USB_KEYBOARD_SIMULATOR
#define	CONF_ESPIAL_SET_CURSOR_SHAPE_SUPPORT
#define	CONF_ESPIAL_CPU_LIMIT
#define	CONF_OSD_ENGINE_DFB_DOUBLE_BUFFER
#define	CONF_OSD_ENGINE_STATIC_IMAGE_BUF_SIZE	1048576
#define	CONF_OSD_ENGINE_HTTP_IMAGE
#define	CONF_ENGINE_HAL
#define	CONF_BG_ON_OSD
#define	CONF_OSD_IMG_CACHE_LARGE	3
#define	CONF_OSD_IMG_CACHE_MEDIUM	24
#define	CONF_OSD_IMG_CACHE_SMALL	16
#define	CONF_OSD_IMG_CACHE_LARGE_THRES	345600
#define	CONF_OSD_IMG_CACHE_MEDIUM_THRES	6400
#define	CONF_MAX_THUMB_CATCH_SIZE	3145728
#define	CONF_MAX_THUMB_CATCH_NUMBER	10000
#define	CONF_DRAW_OSD_TEXT_BY_ALE
#define	CONF_ALE_TEXT_CACHE_SIZE	1048576
#define	CONF_THUMBNAIL_CACHE_ON_STORAGE_FOLDER	""
#define	CONF_CAS_BROWSE_DATE_DESCEND
#define	CONF_DMA_HD_UI
#define	CONF_DMA_DEPTH32
#define	CONF_THEME_SCREENSHOT	""
#define	CONF_THEME_THUMBNAIL	""
#define	CONF_DEFAULT_THEME	""
#define	CONF_DEFAULT_DESKTOP	""
#define	CONF_ONLINE_IMAGE_LOCAL_PATH	"/tmp/local_file"
#define	CONF_CROSSBAR_EXCHANGE_DIRECTION
#define	CONF_ALPHA_UI_STYLE
#define	CONF_LAVENDER_UI
#define	CONF_OSD_FADING_UI_EFFECT
#define	CONF_OSD_HOME_CROSSBAR_V2
#define	CONF_OSD_HOME_CROSSBAR_V2_MODE1
#define	CONF_QUICK_SHOW_BG	"image/reboot_animation.jpg"
#define	CONF_OSD_WIDTH	1280
#define	CONF_OSD_HEIGHT	720
#define	CONF_JPEG_THUMBNAIL_MAX_W	240
#define	CONF_JPEG_THUMBNAIL_MAX_H	240
#define	CONF_MAX_SUPPORTED_PROGRESSIVE_JPEG_SIZE	345600
#define	CONF_MAX_SUPPORTED_THUMBNAIL_PNG_SIZE	345600
#define	CONF_MAX_SUPPORTED_THUMBNAIL_GIF_SIZE	345600
#define	CONF_GFX
#define	CONF_GFX_WAIT_FOR_COMMAND
#define	CONF_DISABLE_VIDEO_OUTPUT_IN_POWER_OFF
#define	CONF_ENABLE_HOME_PLAYING_INFO
#define	CONF_QUICK_MENU
#define	CONF_OPTION_MENU
#define	CONF_OSD_ENABLE_SCREENSAVER
#define	CONF_OSD_STANDBY_MODE_TIMEOUT	""
#define	CONF_THUMB_VARIOUS_EXTRACT_SUPPORT
#define	CONF_SLIDESHOW_INTERVAL	3
#define	CONF_PREV_NEXT_AS_PGUP_PGDN
#define	CONF_SPLASH_SCREEN_NTSC_PAL_SWITCH
#define	CONF_EZBOOT_SUPPORT_FAIL_SAFE_SPLASH_SCREEN
#define	CONF_USING_WIZARD
#define	CONF_OSD_SUPPORT_PREVIEW_PAGE
#define	CONF_PREVIEW_WINDOW_IOM
#define	CONF_OSD_PREVIEW_WIN_X	167
#define	CONF_OSD_PREVIEW_WIN_Y	162
#define	CONF_OSD_PREVIEW_WIN_W	335
#define	CONF_OSD_PREVIEW_WIN_H	237
#define	CONF_SHOW_BROWSE_PAGE_TITLE_ICON
#define	CONF_ORG_AUDIO_SHOW_INFO_STYLE
#define	CONF_AUDIO_SHOW_INFO_STYLE_IN_VIDEO_PAGE	0
#define	CONF_ORG_SUBTITLE_SHOW_INFO_STYLE
#define	CONF_SUBTITLE_SHOW_INFO_STYLE_IN_VIDEO_PAGE	0
#define	CONF_ENHANCED_PAGE_OBJECT
#define	CONF_DIGITAL_WITHOUT_HDMI_AUDIO
#define	CONF_KEYBOARD_SUPPORT_EU
#define	CONF_SINGLE_RENDERER
#define	CONF_INDEPENDENT_BROWSE_DISPLAY
#define	CONF_PHOTO_BROWSE_DISPLAY_DEFAULT_IS_LIST
#define	CONF_VIDEO_BROWSE_DISPLAY_DEFAULT_IS_THUMBNAIL
#define	CONF_MUSIC_BROWSE_DISPLAY_DEFAULT_IS_LIST
#define	CONF_HOME_CROSSBAR_DEFAULT_IS_VIDEO
#define	CONF_DISABLE_CONTROL_OSD_FROM_STD_INPUT
#define	CONF_DMA_HDMI
#define	CONF_MULTI_LANGUAGE
#define	CONF_DISABLE_HOME_AND_RETURN_WHILE_VIDEO_PLAYING
#define	CONF_DMA_SUBTITLE
#define	CONF_ZOOM_IN_OUT_CASE1
#define	CONF_DISABLE_SUBTITLE_IN_ZOOM
#define	CONF_PLAYER_CHAPTER_SUPPORT
#define	CONF_MKV_CHAPTER_SUPPORT
#define	CONF_HDMI_ALWAYS_OUTPUT_RGB
#define	CONF_HDMI_3_7_1_fix_FPE
#define	CONF_VIDEO_QUICK_JUMP
#define	CONF_PICTURE_AUTO_ORIENTATION
#define	CONF_ADDITIONAL_ENCODING_SUPPORT
#define	CONF_HD_PHOTO_PLAYER
#define	CONF_GIF_PLAY_SINGLE_FRAME
#define	CONF_TIFF_PLAY_SINGLE_FRAME
#define	CONF_NTSC_PAL_SWITCHING
#define	CONF_NTSC_OR_PAL_UNUPGRADABLE
#define	CONF_LOCAL_BROWSE
#define	CONF_LOCAL_PLAYLIST
#define	CONF_LOCAL_PLAYLIST_PARSE_BUFFER_SIZE	102400
#define	CONF_SLIDE_SHOW_SECOND_INDEX_0_IS	3
#define	CONF_SLIDE_SHOW_1_MIN_INDEX	28
#define	CONF_SLIDE_SHOW_2_MINS_INDEX	"29"
#define	CONF_THUMB_WMA
#define	CONF_THUMB_MP4
#define	CONF_DMA_AUDIO_ALBUM_ART
#define	CONF_DMA_LOCAL_BROWSE_THUMB
#define	CONF_LOCAL_THUMBNAIL_MAX_SIZE	102400
#define	CONF_DMA_AUDIO_TRACK_SWITCH
#define	CONF_DMA_FONT_FREETYPE2
#define	CONF_ENABLE_LOGO4WMC
#define	CONF_SAFE_MODE
#define	CONF_BROWSE_HANDLER
#define	CONF_BROWSE_CACHE
#define	CONF_USE_SERVER_HANDLER
#define	CONF_PHOTO_SLIDESHOW_NO_RESUME_PLAYING_WITH_PREV_NEXT
#define	CONF_FILEOP
#define	CONF_SUPPORT_AUTO_MOVE_WITH_PLAYLIST
#define	CONF_QUICK_START_MODE
#define	CONF_LAST_PARTITION_NODE_NAME	""
#define	CONF_STATIC_CONFIG_MOUNT_POINT	""
#define	CONF_SUPPORT_DEEP_SLEEP_MODE
#define	CONF_DEBOUNCE_NTSC_PAL_KEY_TIME	10
#define	CONF_THERMAL_SENSOR_SUPPORT
#define	CONF_THERMAL_HIGH_TEMPERATURE	65
#define	CONF_THERMAL_LOW_TEMPERATURE	50
#define	CONF_RTC_TOOL
#define	CONF_NTSC_OR_PAL	"NTSC"
#define	CONF_NTSC_M
#define	CONF_SUPPORT_COMPONENT_OUTPUT_IN_TVDOCK
#define	CONF_HDMI_LOCK_FUNCTION
#define	CONF_APPLY_DISPLAY_IF_ASPECT_RATIO_CHANGED
#define	CONF_IRDA_DFB_EVENT
#define	CONF_REMOTE_IOM_WITH_KEYBOARD
#define	CONF_STORAGE_SUPPORT
#define	CONF_REMOVABLE_DEVICE_MANAGER
#define	CONF_NTFS_SUPPORT
#define	CONF_NTFS_3G_SUPPORT
#define	CONF_FAT_SUPPORT
#define	CONF_DOSFSTOOLS
#define	CONF_HFS_SUPPORT
#define	CONF_EXT2_SUPPORT
#define	CONF_EXT3_SUPPORT
#define	CONF_MOUNT_LOCAL_SATA_DRIVE
#define	CONF_USB_MNT_ROOT	"/tmp/media/usb"
#define	CONF_MNT_POINT_FOR_SATA	"Local"
#define	CONF_EXPORT_STORAGE_MNT_POINT	"/tmp/media/export"
#define	CONF_USB_MNT_POINT_FOR_PORT1	"USB1"
#define	CONF_USB_MNT_POINT_FOR_PORT2	"USB2"
#define	CONF_USB_MNT_POINT_FOR_PORT	"USB"
#define	CONF_REMOVABLE_DEVICE_MANAGER_VIRTUAL_FOLDER_FOR_LOCAL_BROWSE
#define	CONF_REMOVABLE_DEVICE_MANAGER_VF_LINKLIST
#define	CONF_REMOVABLE_DEVICE_MANAGER_VF_SUPPORT_INOTIFY
#define	CONF_REMOVABLE_DEVICE_MANAGER_VF_INOTIFY_REFRESH_DELAY	30
#define	CONF_REMOVABLE_DEVICE_MANAGER_VIRTUAL_FOLDER_FOR_LOCAL_BROWSE_PATH	""
#define	CONF_ONE_DEVICE_FOR_EACH_USB_PORT
#define	CONF_CAS
#define	CONF_CAS_FOR_SATA_USB
#define	CONF_TVDOCK_DB_DIR	"/.iom/"
#define	CONF_TVDOCK_DB_NAME	"iom.cas"
#define	CONF_TVDOCK_UNION_DB_NAME	"uniondb.cas"
#define	CONF_TVDOCK_DB_MD5	".md5"
#define	CONF_CAS_FOLDER_CRC
#define	CONF_CAS_TIMER_INTERVAL	10
#define	CONF_MEDIA_LIBRARY_WITHOUT_AGGREGATION
#define	CONF_REMOVABLE_DEVICE_BROWSE
#define	CONF_PTP_SUPPORT
#define	CONF_PTP_EXPORT_ONLY_IMAGE
#define	CONF_GPHOTO2_IDLIST	""
#define	CONF_MAX_NUM_USB_DRIVES	3
#define	CONF_SPU_API
#define	CONF_FONT_FILE_PATH_STORE	"/tmp/font_file_path"
#define	CONF_SUPPORT_MICRODVD_SUBTITLE
#define	CONF_AVI_SUPPORT_MULTIAUDIO_STREAM
#define	CONF_DMA_MLP_BOUNDED_WITH_RND
#define	CONF_PROCPIPE_PLAYER
#define	CONF_HW_BUFFERING
#define	CONF_ISO_FOLDER_SUPPORTED
#define	CONF_DTS_6CH_DIGITAL_COMPRESSED
#define	CONF_DTS_HRA_2CH_DIGITAL_COMPRESSED
#define	CONF_DTS_HRA_6CH_DIGITAL_COMPRESSED
#define	CONF_DTS_MA_2CH_DIGITAL_COMPRESSED
#define	CONF_DTS_MA_6CH_DIGITAL_COMPRESSED
#define	CONF_DOLBY_LL_2CH_ANALOG_COMPRESSED
#define	CONF_DOLBY_LL_2CH_DIGITAL_COMPRESSED
#define	CONF_DOLBY_LL_6CH_ANALOG_COMPRESSED
#define	CONF_DOLBY_LL_6CH_DIGITAL_COMPRESSED
#define	CONF_DOLBY_PLUS_6CH_DIGITAL_COMPRESSED
#define	CONF_AC3_6CH_DIGITAL_COMPRESSED
#define	CONF_AAC_6CH_DIGITAL_COMPRESSED
#define	CONF_WMAPRO_6CH_DIGITAL_COMPRESSED
#define	CONF_PCM_FILE_SUPPORTED
#define	CONF_MUSIC_DIFFERENT_SPEED
#define	CONF_MUSIC_OGG
#define	CONF_MUSIC_FLAC
#define	CONF_FORMAT_MATROSKA
#define	CONF_SMOOTH_FASTFORWARD
#define	CONF_DMA_HW_AES
#define	CONF_PIPE_SG_PSF_PLAYER
#define	CONF_PIPE_AVI_PLAYER
#define	CONF_SPLIT_MEDIALOGIC
#define	CONF_PLAYER_NOTUSE_DEVICE_MEM
#define	CONF_HD_GFX_PHOTO_PLAYER
#define	CONF_BUFFER_WIDTH_FOR_HD_GFX_PHOTO_PLAYER	2047
#define	CONF_BUFFER_HEIGHT_FOR_HD_GFX_PHOTO_PLAYER	2047
#define	CONF_SCREEN_WIDTH_FOR_HD_GFX_PHOTO_PLAYER	1920
#define	CONF_SCREEN_HEIGHT_FOR_HD_GFX_PHOTO_PLAYER	1080
#define	CONF_SCREEN_NORNAL_WIDTH_FOR_HD_GFX_PHOTO_PLAYER	1440
#define	CONF_SCREEN_NORNAL_HEIGHT_FOR_HD_GFX_PHOTO_PLAYER	1080
#define	CONF_HW_PHOTO_DECODER
#define	CONF_MULTI_PLAYER_CACHE
#define	CONF_MULTI_PLAYER_CACHE_FOR_AV_PLAYER
#define	CONF_MULTI_PLAYER_CACHE_FOR_PIC_PLAYER
#define	CONF_MULTI_PLAYER_CACHE_SIZE	77
#define	CONF_QUICKTIME_PLAYER
#define	CONF_DIVX_SUBTITLE_SUPPORT
#define	CONF_FLV_PLAYER
#define	CONF_M4V_SUPPORT_TRICKMODE
#define	CONF_PGS_SUBTITLE_SUPPORT
#define	CONF_SW_DEMUX_PLAYER
#define	CONF_YOUTUBE_MOV_CACHE_PLAYER
#define	CONF_SW_DEFAULT_BPS_FOR_YOUTUBE	32768
#define	CONF_SW_MIN_BUFFERING_TIME_FOR_YOUTUBE	1
#define	CONF_SW_MAX_BUFFERING_TIME_FOR_YOUTUBE	15
#define	CONF_SW_FIRST_MAX_BUFFERING_TIME_FOR_YOUTUBE	6
#define	CONF_DIVX_CERTIFICATION
#define	CONF_DIVX_DEFAULT_KEY
#define	CONF_DIVX_DRM_SUPPORTED_VERSION	2
#define	CONF_OSDKEY_MAPPING
#define	CONF_KEYBOARD_IR_INJECTION
#define	CONF_WIZARD_IGNORE_QUEST_SERVER
#define	CONF_VOLUME_RNAGE_WORKAROUND
#define	CONF_DEFAULT_VOLUME	50
#define	CONF_VOLUME_SHOW_TIME	4
#define	CONF_OSD_VOLUME_KEY_WORK
#define	CONF_UNIFORM_BROWSE
#define	CONF_SAVEMETHOD_CRC
#define	CONF_MAX_FILE_PATH_LENGTH	4353
#define	CONF_HTTP_HEADER_KEEP_ORIGINAL_HOSTNAME
#define	CONF_ACCOUNT_MGR
#define	CONF_ACCOUNT_FACTORY_SETTINGS	"account_list.xml"
#define	CONF_ACCOUNT_MSG_ONLING_YOUTUBE_SEARCH_MAX_ITEMS	50
#define	CONF_ACCOUNT_MGR_LOCAL_SAMBA_MAX_ITEMS	10
#define	CONF_ACCOUNT_MGR_LOCAL_NFS_MAX_ITEMS	10
#define	CONF_EMERGENCY_FIRMWARE_UPGRADE
#define	CONF_DMA_GPIO_API
#define	CONF_DEBUG_SECRET_TELNETD
#define	CONF_DMALLOC_LOGFILE_DIR	""
#define	CONF_NO_SIGPIPE
#define	CONF_SHOW_INFO_BAR_WHILE_SWITCHING_REPEAT_MODE
#define	CONF_OSD_INFO_INDEPENDENCE
#define	CONF_BUG_2134_FIXED
#define	CONF_BUG_1332_FIXED
#define	CONF_BUG_798_FIXED
#define	CONF_BUG_1189_FIXED
#define	CONF_BUG_1767_FIXED
#define	CONF_BUG_1943_FIXED
#define	CONF_BUG_2972_FIXED
#define	CONF_SMALL_FOLDER_ICON_FOR_FOLDER_THUMB
#define	CONF_SUBTITLE_TURN_ON_OR_OFF_BY_DEFAULT
#define	CONF_AUDIO_PLAYLIST
#define	CONF_AUDIO_TRACK_DISPLAY
#define	CONF_AUDIO_HIERARCHY_BROWSE
#define	CONF_SEND_MUTE_SOUND_AT_BEGINNING
#define	CONF_DLNA_CHOOSE_TRANSCODED_URI_FOR_WTV
#define	CONF_DMA_MS_JANUS
#define	CONF_DMA_MS_JANUS_SIGMA
#define	CONF_DMA_DRM_STORE_IN_HDD	"/tmp/drm"
#define	CONF_RALLY
#define	CONF_SUPPORT_WMAPRO_IN_DEVICE_DESCRIPTION
#define	CONF_SETTING_ORIGINAL_CONFIG_FILE_DIR	"/conf_src"
#define	CONF_SETTING_FACTORY_SETTINGS	"config_factory_default"
#define	CONF_SETTING_CONFIG_FILE_DIR	"/tmp/conf/"
#define	CONF_SETTING_CONFIG_FILE_NAME	"config"
#define	CONF_RELATIVE_PATH_FOR_RESOURCES	""
#define	CONF_ROOTFS_SKELETON_GENERIC
#define	CONF_INSTALL_GLIBC
#define	CONF_UCLIBC_VERSION	""
#define	CONF_GLIBC_2_8
#define	CONF_GLIBC_VERSION	"2.8_by_mips_4_3_2"
#define	CONF_BUSYBOX
#define	CONF_BUSYBOX_1_10_0
#define	CONF_BUSYBOX_1_10_0_CONFIG_FOR_NETWORKING
#define	CONF_BUSYBOX_VERSION	"1.10.0"
#define	CONF_ROOTFS_PRIMARY_SYSTEM_SKELETON_GENERIC
#define	CONF_BUSYBOX_PRIMARY_SYSTEM
#define	CONF_BUSYBOX_PRIMARY_SYSTEM_1_10_0
#define	CONF_BUSYBOX_PRIMARY_SYSTEM_1_10_0_CONFIG_GENERIC_WITH_MODULES
#define	CONF_BUSYBOX_PRIMARY_SYSTEM_VERSION	"1.10.0"
#define	CONF_SYSCONFIG_USING_SQUASHFS
#define	CONF_FIRMWARE_UPGRADE_PLUGIN
#define	CONF_SYSCONFIG_PATH	"sysconfig"
#define	CONF_SYSCONFIG_FIRMWARE_NAME_COMPARE
#define	CONF_FIRMWARE_WDTV_SMP8654_WISTRON
#define	CONF_FIRMWARE_SCRIPT	"firmware_script_wdtv_smp8654_wistron.mk"
#define	CONF_FIRMWARE_FULL_UPGRADE_SMP8654
#define	CONF_FIRMWARE_SERVER	"http://www.iomega.com/support/up-dx/"
#define	CONF_FIRMWARE_SERVER_USRPWD	""
#define	CONF_FIRMWARE_VER_FILE	"iomx2.ver"
#define	CONF_FIRMWARE_BIN_FILE	"iomx2.bin"
#define	CONF_FIRMWARE_FULL_FILE	"iomx2.fff"
#define	CONF_FIRMWARE_PACKAGE_FILE	"iomx2.pkg"
#define	CONF_FIRMWARE_PLUGIN_TYPE_LEGACY
#define	CONF_FWUP_MEM_POOL_SIZE	23068672
#define	CONF_NAND_FLASH_SIZE	268435456
#define	CONF_NAND_IMAGE_NO_YAMON
#define	CONF_BOOTLOADER_MTD_PARTITION	"/dev/sigmblocka"
#define	CONF_BOOTLOADER_MTD_SIZE	131072
#define	CONF_BOOTLOADER_UPGRADE
#define	CONF_MTD_BEFORE_YAMON_SIZE	524288
#define	CONF_MTD_YAMON_SIZE	262144
#define	CONF_DUAL_KERNEL
#define	CONF_KERNEL_MTD_PARTITION	"/dev/sigmblockd"
#define	CONF_KERNEL_MTD_MIRROR_PARTITION	"/dev/sigmblocke"
#define	CONF_MTD_IMAT_PARTITION	"/dev/sigmblockf"
#define	CONF_MTD_IMAT_SIZE	8388608
#define	CONF_MTD_IMAT_UPGRADE
#define	CONF_MTD_XMAT_PARTITION	"/dev/sigmblockg"
#define	CONF_MTD_XMAT_SIZE	8388608
#define	CONF_MTD_XMAT_UPGRADE
#define	CONF_FIRMWARE_MTD_PARTITION	"/dev/sigmblockh"
#define	CONF_FIRMWARE_STORAGE_PARTITION	"/dev/sigmblocki"
#define	CONF_KEYSTORAGE_MTD_PARTITION	""
#define	CONF_KEYSTORAGE_MIRROR_MTD_PARTITION	""
#define	CONF_MIRROR_FOR_SETTINGS
#define	CONF_CONFIG_MTD_PARTITION	"/dev/sigmblockj"
#define	CONF_CONFIG_MIRROR_MTD_PARTITION	"/dev/sigmblockk"
#define	CONF_PRIMARY_SYSTEM_SIZE	4194304
#define	CONF_APP_ROMFS_SIZE	96468992
#define	CONF_STORAGE_PARTITION_SIZE	96468992
#define	CONF_FLASH_BLOCK_SIZE	1048576
#define	CONF_KERNEL_PAGE_SIZE	16384
#define	CONF_FWUP_SEK_FILE	""
#define	CONF_SECURITY_USE_JANUS_SHA1SUM_FILENAME	""
#define	CONF_SECURITY_USE_CPU_KEY_SHA1SUM_FILENAME	""
#define	CONF_SECURITY_USE_IPTOKEN_SHA1SUM_FILENAME	""
#define	CONF_BOOT_AUTH_KEY	""
#define	CONF_BUILD_SIGMA_SDK
#define	CONF_LINUX_KERNEL_VERSION_2_6_22
#define	CONF_LINUX_KERNEL_VERSION_2_6_22_19_36_IOM
#define	CONF_BUILD_ZBOOT
#define	CONF_SQUEEZE_XENV_ZBOOT_YAMON
#define	CONF_FONTS
#define	CONF_FREETYPE
#define	CONF_FREETYPE_2_3_9
#define	CONF_FREETYPE_STATIC_LIB
#define	CONF_FREETYPE_VERSION	"2.3.9"
#define	CONF_FONT_ARPHIC
#define	CONF_FONT_ARPHIC_MOBILE_FONT
#define	CONF_FONTS_VERSION	"arphic_mbf"
#define	CONF_FONTS_LIB_TYPE_ALL
#define	CONF_FONT_SPU_PLAYER_USE_MBF
#define	CONF_DMALLOC_VERSION	""
#define	CONF_FLAC
#define	CONF_FLAC_1_2_1
#define	CONF_FLAC_VERSION	"1.2.1"
#define	CONF_LIBICONV
#define	CONF_LIBICONV_1_12
#define	CONF_LIBICONV_VERSION	"1.12"
#define	CONF_LIBJPEG
#define	CONF_LIBJPEG_V6B
#define	CONF_LIBJPEG_VERSION	"v6b"
#define	CONF_LIBPNG
#define	CONF_LIBPNG_1_2_44
#define	CONF_LIBPNG_VERSION	"1.2.44"
#define	CONF_LIBUNGIF
#define	CONF_LIBUNGIF_4_1_3
#define	CONF_LIBUNGIF_VERSION	"4.1.3"
#define	CONF_ZLIB
#define	CONF_ZLIB_1_2_2
#define	CONF_ZLIB_VERSION	"1.2.2"
#define	CONF_LIBCX
#define	CONF_LIBCX_1_1_1
#define	CONF_LIBCX_VERSION	"1.1.1"
#define	CONF_DIRECTFB
#define	CONF_MICROWIN_VERSION	""
#define	CONF_MICROWIN_CONFIG	""
#define	CONF_TINYXML
#define	CONF_TINYXML_2_5_3
#define	CONF_TINYXML_VERSION	"2_5_3"
#define	CONF_MXML
#define	CONF_MXML_2_6
#define	CONF_MXML_VERSION	"2.6"
#define	CONF_SQLITE
#define	CONF_SQLITE_AMALGAMATION_3_6_11
#define	CONF_SQLITE_VERSION	"3.6.11"
#define	CONF_TIFF
#define	CONF_TIFF_3_7_1
#define	CONF_TIFF_VERSION	"3.7.1"
#define	CONF_TREMOR
#define	CONF_TREMOR_1_0_SVN
#define	CONF_TREMOR_VERSION	"1.0-svn"
#define	CONF_DHCPCD
#define	CONF_DHCPCD_1_3_22_PL1
#define	CONF_DHCPCD_VERSION	"1.3.22-pl1"
#define	CONF_CURL
#define	CONF_CURL_7_20_1
#define	CONF_CURL_VERSION	"7.20.1"
#define	CONF_OPENSSL
#define	CONF_OPENSSL_0_9_8_o
#define	CONF_OPENSSL_VERSION	"0.9.8o"
#define	CONF_MATRIXSSL_VERSION	""
#define	CONF_RSYNC_VERSION	""
#define	CONF_TWONKYMEDIA_SERVER_VERSION	""
#define	CONF_PARAGON_NTFS_VERSION	""
#define	CONF_PARAGON_HFS_FSCK_VERSION	""
#define	CONF_NTFS_3G_2009_4_4
#define	CONF_NTFS_3G_VERSION	"2009.4.4"
#define	CONF_TNTFS_VERSION	""
#define	CONF_NETATALK_VERSION	""
#define	CONF_BERKELEY_DB_VERSION	""
#define	CONF_FLICKR
#define	CONF_XML2
#define	CONF_FONTCONFIG
#define	CONF_HOWL_VERSION	""
#define	CONF_SDPARM
#define	CONF_SMARTMONTOOLS
#define	CONF_NTP
#define	CONF_EXPAT
#define	CONF_UUID_VERSION	""
#define	CONF_PCRE
#define	CONF_PCRE_VERSION	"8.02"
