##############################################################################
# Copyright (C) alphanetworks 2006-- 
# All Rights Reserved -- Company Confidential
# Author: tao_yu@alphanetworks.com 
# mediaplayer top-level Makefile
##############################################################################

############################# global settings section ########################

TOP                 :=$(shell pwd)/../..#

COMPONENT           := mediaplayer

include $(TOP)/Target.mk
include $(TOP)/Target.options



######################## sub directory section  #############################

SUBDIRS      :=

############################# common rules section ###########################

include $(TOP_SCRIPTS_DIR)/rules.mk
