#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "/opt/mips-4.3/bin//mipsel-linux-gcc -fPIC -DOPENSSL_PIC -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -mabi=32 -DL_ENDIAN -DTERMIO -O3 -fPIC -g -Wall"
  #define PLATFORM "linux-mipsel"
  #define DATE "Tue Jul  7 08:16:24 CST 2015"
#endif
