##############################################################################
# Copyright (C) alphanetworks 2006-- 
# All Rights Reserved -- Company Confidential
# Author: wills_yin@alphanetworks.com
# wmc top-level Makefile
##############################################################################

############################# global settings section ########################
TOP        := $(shell pwd)/../..#
COMPONENT  := crypto# comment to remove trailing space 

include $(TOP)/Target.mk
include $(TOP)/Target.options

######################### common rules section #############################

SUBDIRS := aes rsa

include $(TOP_SCRIPTS_DIR)/rules.mk
